bindAddr = "0.0.0.0"
bindPort = 7000
kcpBindPort = 7000

transport.maxPoolCount = 5
tls.force = false

webServer.addr = "127.0.0.1"
webServer.port = 7500
webServer.user = "admin"
webServer.password = "admin"

webServer.pprofEnable = false
enablePrometheus = false

log.to = "console"
log.level = "info"
log.disablePrintColor = false

detailedErrorsToClient = true

auth.method = "token"
auth.token = "12345678"

maxPortsPerClient = 0

udpPacketSize = 1500
natholeAnalysisDataReserveHours = 168
